name:                licross
version:             0.1.0.0
github:              "xaviershay/licross"
license:             GPL-3
author:              "Xavier Shay"
maintainer:          "contact@xaviershay.com"
copyright:           "2018 Xavier Shay"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/xaviershay/licross#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- beam-core
- beam-postgres
- binary
- hashable
- http-types
- lens
- postgresql-simple
- mtl
- random
- servant-server
- servant-rawm
- servant-rawm-server
- stm
- text
- unordered-containers
- wai
- wai-cors
- wai-extra
- warp
- vector

library:
  source-dirs: src

executables:
  licross-server:
    main:                Main.hs
    source-dirs:         app/service
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - licross
    - bytestring
  licross-generate:
    main:                Main.hs
    source-dirs:         app/generator
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - licross

tests:
  licross-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - licross
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-quickcheck
