name:                licross
version:             0.1.0.0
github:              "xaviershay/licross"
license:             GPL-3
author:              "Xavier Shay"
maintainer:          "contact@xaviershay.com"
copyright:           "2018 Xavier Shay"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/xaviershay/licross#readme>

dependencies:
- base >= 4.7 && < 5
- text
- unordered-containers
- hashable
- lens

library:
  source-dirs: src

executables:
  licross-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - licross

tests:
  licross-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - licross
